version: '3.8'

services:
  api:
    build:
      context: ./dist/apps/api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    env_file:
      - apps/api/.env.production
    volumes:
        - ./volumes/logs:/logs
    privileged: true # cấp quyền mount nfs
    ports:
      - 3333:3333
    networks:
      - bridge_net

networks:
  bridge_net:
    external:
      name: custom_net
